version: '3.1'

services:

  jenkins:
    image: istresearch/jenkins:latest
    container_name: jenkins
    user: jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home